### ISSUE TITLE
Can't install fastrepl Windows 10

### ISSUE THREAD

**Issue by hooNpk** [fastrepl/fastrepl#116]
I tried to install fastrepl with the command
` pip install fastrepl `

But the installation process failed
I use python 3.10 on windows 10 and installed it in a virtual environment.

```
It says
Collecting lazy-import<0.3.0,>=0.2.2 (from fastrepl)
  Downloading lazy_import-0.2.2.tar.gz (15 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\johnh\AppData\Local\Temp\pip-install-filhydo3\lazy-import_734567652bf840cb958f06734405e040\setup.py", line 6, in <module>
          readme = infile.read()
      UnicodeDecodeError: 'cp949' codec can't decode byte 0xe2 in position 621: illegal multibyte sequence
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.
```

In my think, The encoding might be not handled correctly somewhere.

**Comment by yujonglee** [comment]
@hooNpk 
Thanks for raising. 

By any chance, could you please try visiting https://github.com/mnmelo/lazy_import/pull/23#issuecomment-1275499740 and see if it helps?

**Comment by hooNpk** [comment]
It worked!
For other windws users...

1. Win + R
2. execute ` intl.cpl `
3. `Administrative` tab
4. Click the `Change system local` button
5. Enable `Beta: Use Unicode UTF-8 for worldwide language support `
6. Reboot

**Comment by yujonglee** [comment]
Since we removed `lazy_import`, this is no longer relevant.
