### ISSUE TITLE
How is the tokenizer used? 

### ISSUE THREAD

**Issue by krrishdholakia** [fastrepl/fastrepl#92]
https://github.com/fastrepl/fastrepl/blob/4c80ccd008341aa2081d8edb543645c171e4a6d7/fastrepl/llm.py#L168

**Comment by yujonglee** [comment]
This is for generating `logit_bias`, which helps reliability of simple classification.

https://github.com/fastrepl/fastrepl/blob/7ef185e12b41d29aca869ea4440e5068a3344365/fastrepl/eval/model/utils.py#L17-L33

**Comment by krrishdholakia** [comment]
thanks!

**Comment by yujonglee** [comment]
See https://github.com/BerriAI/litellm/issues/312 for further work on LiteLLM.
